cmd.load('3K37.pdb', '3K37')
cmd.select('NA', '3K37 and chain A')
cmd.select('peramivir', 'resn BCZ and chain A')
cmd.hide('everything')
cmd.show('cartoon', 'NA')
cmd.color('green', 'NA')
cmd.show('spheres', 'peramivir')
cmd.color('magenta', 'peramivir')
for r in [46, 153, 273, 288, 395]:
    cmd.select('res%d' % r, 'resi %d and NA' % r)
    cmd.show('sticks', 'res%d' % r)
    cmd.color('blue', 'res%d' % r)
cmd.color('red', 'res273')
cmd.zoom('NA')
